### ISSUE TITLE
Byte 5129 fails binary test

### ISSUE THREAD

**Issue by crutchcorn** [CunningLogic/SunShine#1]
![](http://media.giphy.com/media/KsgLFgQp7Elj2/giphy.gif)
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/614/631/54b.gif)
![](http://weknowgifs.com/wp-content/uploads/2013/03/billy-dee-williams-clapping.gif)
![](http://38.media.tumblr.com/4dcb32e3d919705576bcf2c4263a5f8c/tumblr_n9uqy2UcXD1rrx588o1_400.gif)
![](http://weknowgifs.com/wp-content/uploads/2013/03/obama-clapping-gif.gif)
![](http://3.bp.blogspot.com/-gCo44AmAGLk/UWgP9Ot56nI/AAAAAAAAQ7I/YsAJLHrKYqw/s1600/ryan-gosling-clap.gif)
![](http://i0.kym-cdn.com/entries/icons/original/000/013/974/clap.gif)
And more

You got me. You got me good. 
_tips hat_ Good day sir.

**Comment by CunningLogic** [comment]
LOLZ INVALID!

**Comment by crutchcorn** [comment]
To be fair, this whole GitHub repo is kinda a troll. None-the-less, a very funny one. Seriously needed the laugh, thanks

**Comment by CunningLogic** [comment]
Indeed you are the first to ever even speak up on it lol, lets call it a place holder not a troll.. one day

**Comment by crutchcorn** [comment]
The URL title of this picture explains my emotions currently.
![](http://www.evilmilk.com/pictures/Do_Not_Tease_Me_Human.jpg)
(the URL is http://www.evilmilk.com/pictures/Do_Not_Tease_Me_Human.jpg btw ;P)
